set loc_province_宁 0
set loc_province_青海 1
set loc_province_内 0
set loc_province_安 0
set loc_province_台湾 1
set loc_province_广西壮族自 0
set loc_province_河南 1
set loc_province_山东 1
set loc_province_四川 1
set loc_province_福建 1
set loc_province_云南 1
set loc_province_安徽省 1
set loc_province_河 0
set loc_province_宁夏回 0
set loc_province_辽 0
set loc_province_西藏自 0
set loc_province_陕西省 1
set loc_province_山西省 1
set loc_province_河北 1
set loc_province_青 0
set loc_province_海南省 1
set loc_province_四 0
set loc_province_云南省 1
set loc_province_西藏 1
set loc_province_辽宁 1
set loc_province_贵州 1
set loc_province_陕西 1
set loc_province_江苏 1
set loc_province_新疆 1
set loc_province_浙江 1
set loc_province_湖北 1
set loc_province_新疆维吾 0
set loc_province_宁夏回族自治区 1
set loc_province_广东 1
set loc_province_黑龙江省 1
set loc_province_河南省 1
set loc_province_广西壮族 1
set loc_province_贵 0
set loc_province_湖南省 1
set loc_province_广西壮族自治区 1
set loc_province_贵州省 1
set loc_province_新疆维吾尔 1
set loc_province_湖南 1
set loc_province_浙 0
set loc_province_江 0
set loc_province_江西省 1
set loc_province_宁夏回族 1
set loc_province_山东省 1
set loc_province_海南 1
set loc_province_陕 0
set loc_province_广 0
set loc_province_福建省 1
set loc_province_西藏自治 0
set loc_province_宁夏回族自 0
set loc_province_福 0
set loc_province_云 0
set loc_province_甘 0
set loc_province_江西 1
set loc_province_广东省 1
set loc_province_黑龙江 1
set loc_province_甘肃省 1
set loc_province_广西壮 0
set loc_province_台湾省 1
set loc_province_江苏省 1
set loc_province_内蒙古自治 0
set loc_province_青海省 1
set loc_province_宁夏 1
set loc_province_广西壮族自治 0
set loc_province_湖 0
set loc_province_内蒙古 1
set loc_province_内蒙古自治区 1
set loc_province_河北省 1
set loc_province_四川省 1
set loc_province_山西 1
set loc_province_吉 0
set loc_province_黑龙 0
set loc_province_新疆维吾尔自 0
set loc_province_新 0
set loc_province_新疆维 0
set loc_province_新疆维吾尔自治区 1
set loc_province_浙江省 1
set loc_province_广西 1
set loc_province_新疆维吾尔自治 0
set loc_province_甘肃 1
set loc_province_海南岛 1
set loc_province_西藏自治区 1
set loc_province_内蒙 0
set loc_province_吉林 1
set loc_province_内蒙古自 0
set loc_province_辽宁省 1
set loc_province_黑 0
set loc_province_安徽 1
set loc_province_吉林省 1
set loc_province_宁夏回族自治 0
set loc_province_山 0
set loc_province_台 0
set loc_province_海 0
set loc_province_湖北省 1
set loc_province_西 0
